---
abstract: 'Boolean support for Perl'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: boolean
name: boolean
no_index:
  directory:
    - inc
    - t
recommends:
  Readonly: 0
requires:
  perl: 5.005003
resources:
  homepage: https://github.com/ingydotnet/boolean-pm/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/ingydotnet/boolean-pm.git
    web: https://github.com/ingydotnet/boolean-pm/tree
version: 0.29
