---
abstract: 'Boolean support for Perl'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: boolean
no_index:
  directory:
    - inc
    - t
recommends:
  Readonly: 0
  autobox: 0
requires:
  perl: 5.005003
resources:
  license: http://dev.perl.org/licenses/
version: 0.25
